# Numpy Basics

Welcome to section of Numpy and Pandas. This is the most used Python libraries for data science. NumPy consists of a powerful data structure called multidimensional arrays. Pandas is another powerful Python library that provides fast and easy data analysis platform.

NumPy is a library written for scientific computing and data analysis. It stands for numerical python and also known as array oriented computing.

The most basic object in NumPy is the ndarray, or simply an array which is an n-dimensional, homogeneous array. By homogenous, we mean that all the elements in a NumPy array have to be of the same data type, which is commonly numeric (float or integer).


 # Why Numpy?
 convenience & speed
 
 Numpy is much faster than the standard python ways to do computations.
 
Vectorised code typically does not contain explicit looping and indexing etc. (all of this happens behind the scenes, in precompiled C-code), and thus it is much more concise.

Also, many Numpy operations are implemented in C which is basically being executed behind the scenes, avoiding the general cost of loops in Python, pointer indirection and per-element dynamic type checking. The speed boost depends on which operations you're performing.
 
 NumPy arrays are more compact than lists, i.e. they take much lesser storage space than lists

In [3]:
l1 = [1,2,3]
print(l1.__sizeof__())
l2 = [4,5,6]
c =[]
for i in range(len(l1)):
    a =l1[i]+l2[i]
    c.append(a)
print(c)

64
[5, 7, 9]


In [2]:
l1 = [1,2,3]
l2 = [4,5,6]
c =[]
c = [l1[i]+l2[i] for i in range(len(l1)) ] # list compreshasation
c

[5, 7, 9]

In [1]:
import numpy

In [4]:
a = numpy.array([1,2,3])
print(a.__sizeof__())
b = numpy.array([4,5,6])
a+b

108


array([5, 7, 9])

In [3]:
numpy.array([[1,2,3.0],[4,5,6]])

array([[1., 2., 3.],
       [4., 5., 6.]])

In [4]:
import numpy as np

In [6]:
a = np.array([1,2,3])

In [7]:
a

array([1, 2, 3])

In [8]:
b = np.array([[1.0,2.0,3.3],[4.6,5.9,6.9],[3,8,9]])

In [9]:
b

array([[1. , 2. , 3.3],
       [4.6, 5.9, 6.9],
       [3. , 8. , 9. ]])

In [10]:
b.shape

(3, 3)

In [11]:
a = np.array([[1,2,3]])

In [12]:
a.shape

(1, 3)

In [15]:
a.dtype

dtype('int32')

In [16]:
b.ndim

2

In [17]:
a.ndim

2

In [18]:
type(a)

numpy.ndarray

In [21]:
type(b)

numpy.ndarray

In [19]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(2,20,3)

array([ 2,  5,  8, 11, 14, 17])

# Performance measurement
I mentioned that the key advantages of numpy are convenience and speed of computation.

You'll often work with extremely large datasets, and thus it is important point for you to understand how much computation time (and memory) you can save using numpy, compared to standard python lists.

In [22]:
c=range(3) # [0,1,2] ---> [0,1,8]
l =[i**3  for i  in c]
l

[0, 1, 8]

In [23]:
c = np.arange(3) # [0,1,2]
d =c**3
d

array([0, 1, 8], dtype=int32)

In [26]:
c = range(100000)  # [0,1,2,3,4---------99999] ---> [0,1,8,27,64----]
%timeit[i**3 for i in c]


82.8 ms ± 1.93 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [27]:
c = np.arange(100000)
%timeit c**3


354 µs ± 8.18 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [28]:
l =[1,5,8,9]
[i*9 for i in l]

[9, 45, 72, 81]

In [29]:
c_numpy = np.arange(100000)
%timeit c_numpy**3

361 µs ± 13.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


Still not convinced? want to see one more intresting example

In [30]:
l1 = range(10000)
l2 = [i**2 for i in range(10000)]

In [31]:
l1

range(0, 10000)

In [33]:
a = np.arange(10000)
a**2

array([       0,        1,        4, ..., 99940009, 99960004, 99980001],
      dtype=int32)

In [34]:
l1=[1,2,3]
l2 =[4,5,6]
[l1[i]*l2[i] for i in range(len(l1))]

[4, 10, 18]

In [35]:
fun = lambda x : x*2
fun(89)

178

In [37]:
%timeit list(map(lambda x, y: x*y, l1, l2))

1.67 µs ± 79.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [6]:
import numpy as np
l1 = [1,2,3]
l2 = [4,5,6]
a1 = np.array(l1)
b1 = np.array(l2)

In [7]:
a1

array([1, 2, 3])

In [8]:
b1

array([4, 5, 6])

In [9]:
%timeit a1*b1

1.1 µs ± 101 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [10]:
a1

array([1, 2, 3])

In [11]:
a1 * a1

array([1, 4, 9])

so I can do everything without even writing a loop? yes... ohh wao

# Creating Numpy array

There are multiple ways to create numpy array. Lets walk over them

In [44]:
np.arange(2,12)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [45]:
np.arange(2,12,2)

array([ 2,  4,  6,  8, 10])

In [6]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [50]:
np.ones((4,3),int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [53]:
np.eye(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [54]:
np.full((5,4),9)

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

In [57]:
np.full((7,6),8.9,dtype=int)

array([[8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8]])

In [58]:
np.diag([7,9,8,1,6,8,5])

array([[7, 0, 0, 0, 0, 0, 0],
       [0, 9, 0, 0, 0, 0, 0],
       [0, 0, 8, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 6, 0, 0],
       [0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 5]])

In [62]:
v = np.array([1,2])
a =np.tile(v,(4,5)) # stack 4*5 copies of v on top of each other
print(a)
print(a.ndim)

[[1 2 1 2 1 2 1 2 1 2]
 [1 2 1 2 1 2 1 2 1 2]
 [1 2 1 2 1 2 1 2 1 2]
 [1 2 1 2 1 2 1 2 1 2]]
2


In [85]:

# between 0 and 1
np.random.random()

0.60527488973464

In [102]:
# so let say I want a random value between 0and 50
50*np.random.random()

20.144418186787433

In [111]:
# so let say I want a random value between 10and 50
10+ 40*np.random.random()

42.701706051503486

In [112]:
np.random.random([3,3])

array([[0.87164721, 0.33104424, 0.34094242],
       [0.51120035, 0.23133568, 0.53767858],
       [0.86720411, 0.37175652, 0.12411328]])

In [8]:
import numpy as np
# 100 values between 1 and 50
a = np.linspace(1,50,100)
a
print(len(a))
print(a)

100
[ 1.          1.49494949  1.98989899  2.48484848  2.97979798  3.47474747
  3.96969697  4.46464646  4.95959596  5.45454545  5.94949495  6.44444444
  6.93939394  7.43434343  7.92929293  8.42424242  8.91919192  9.41414141
  9.90909091 10.4040404  10.8989899  11.39393939 11.88888889 12.38383838
 12.87878788 13.37373737 13.86868687 14.36363636 14.85858586 15.35353535
 15.84848485 16.34343434 16.83838384 17.33333333 17.82828283 18.32323232
 18.81818182 19.31313131 19.80808081 20.3030303  20.7979798  21.29292929
 21.78787879 22.28282828 22.77777778 23.27272727 23.76767677 24.26262626
 24.75757576 25.25252525 25.74747475 26.24242424 26.73737374 27.23232323
 27.72727273 28.22222222 28.71717172 29.21212121 29.70707071 30.2020202
 30.6969697  31.19191919 31.68686869 32.18181818 32.67676768 33.17171717
 33.66666667 34.16161616 34.65656566 35.15151515 35.64646465 36.14141414
 36.63636364 37.13131313 37.62626263 38.12121212 38.61616162 39.11111111
 39.60606061 40.1010101  40.5959596  41.09090909

In [114]:
len(a)

100

In [4]:
#memory used by each array element in bytes
a.itemsize
#a.shape


8

In [117]:
np.arange(24)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [1]:
import numpy as np
np.arange(24).reshape(4,-1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [12]:
# -1 will automatically adjust dimention
np.arange(18).reshape(2,3,-1)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

# accessing Numpy array element

In [122]:
a = np.array([2,4,6,8,10,12,14,16])


In [123]:
a

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [124]:
a[2]


6

In [125]:
a[[2,4]]

array([ 6, 10])

In [126]:
a[2:]

array([ 6,  8, 10, 12, 14, 16])

In [127]:
a[2:5]

array([ 6,  8, 10])

In [129]:
a[1::2]

array([ 4,  8, 12, 16])

Lets check the same for 2 D array

In [134]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [135]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [136]:
a[2,2]

9

In [137]:
a > 2

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [138]:
a[a > 2]

array([3, 4, 5, 6, 7, 8, 9])

In [139]:
a[(a > 2) & (a < 5)]

array([3, 4])

In [140]:
b = a

In [141]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [142]:
b[0] = 11

In [143]:
b

array([[11, 11, 11],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [144]:
# Notice a is also changed
a

array([[11, 11, 11],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [145]:
np.shares_memory(a,b)

True

In [146]:
a = np.arange(10)

In [147]:
b = a.copy()

In [148]:
b[0] = 11

In [149]:
b

array([11,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [150]:
np.shares_memory(a,b)

False

In [151]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# More operations

In [152]:
a = np.array([[1,2,3],[4,5,6]])

In [153]:
a


array([[1, 2, 3],
       [4, 5, 6]])

In [154]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [155]:
b = np.array([[7,8,9],[10,5,12]])

In [156]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [157]:
b


array([[ 7,  8,  9],
       [10,  5, 12]])

In [158]:
a == b

array([[False, False, False],
       [False,  True, False]])

In [159]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10,  5, 12]])

In [160]:
np.hstack((a,b))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10,  5, 12]])

# MAthmatical operation

In [161]:
a = np.arange(1,10)

In [162]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [163]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [164]:
np.exp(a)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [165]:
np.sum(a)

45

In [166]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [167]:
np.median(a)

5.0

In [168]:
a.std()

2.581988897471611

In [169]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [175]:
import numpy as np
a=np.arange(1,10)

In [176]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
b = np.array([[1,3],[4,5]])
np.linalg.det(b)

-6.999999999999999

In [15]:
np.linalg.det(a)

LinAlgError: 1-dimensional array given. Array must be at least two-dimensional

In [223]:
np.linalg.det(a)
help(np.linalg.det)

Help on function det in module numpy.linalg:

det(a)
    Compute the determinant of an array.
    
    Parameters
    ----------
    a : (..., M, M) array_like
        Input array to compute determinants for.
    
    Returns
    -------
    det : (...) array_like
        Determinant of `a`.
    
    See Also
    --------
    slogdet : Another way to represent the determinant, more suitable
      for large matrices where underflow/overflow may occur.
    
    Notes
    -----
    
    .. versionadded:: 1.8.0
    
    Broadcasting rules apply, see the `numpy.linalg` documentation for
    details.
    
    The determinant is computed via LU factorization using the LAPACK
    routine z/dgetrf.
    
    Examples
    --------
    The determinant of a 2-D array [[a, b], [c, d]] is ad - bc:
    
    >>> a = np.array([[1, 2], [3, 4]])
    >>> np.linalg.det(a)
    -2.0
    
    Computing determinants for a stack of matrices:
    
    >>> a = np.array([ [[1, 2], [3, 4]], [[1, 2], [2, 1]], [[1, 3]

In [58]:
print(np.linalg.inv(a))
help(np.linalg.inv)

Help on function inv in module numpy.linalg.linalg:

inv(a)
    Compute the (multiplicative) inverse of a matrix.
    
    Given a square matrix `a`, return the matrix `ainv` satisfying
    ``dot(a, ainv) = dot(ainv, a) = eye(a.shape[0])``.
    
    Parameters
    ----------
    a : (..., M, M) array_like
        Matrix to be inverted.
    
    Returns
    -------
    ainv : (..., M, M) ndarray or matrix
        (Multiplicative) inverse of the matrix `a`.
    
    Raises
    ------
    LinAlgError
        If `a` is not square or inversion fails.
    
    Notes
    -----
    
    .. versionadded:: 1.8.0
    
    Broadcasting rules apply, see the `numpy.linalg` documentation for
    details.
    
    Examples
    --------
    >>> from numpy.linalg import inv
    >>> a = np.array([[1., 2.], [3., 4.]])
    >>> ainv = inv(a)
    >>> np.allclose(np.dot(a, ainv), np.eye(2))
    True
    >>> np.allclose(np.dot(ainv, a), np.eye(2))
    True
    
    If a is a matrix object, then the return valu

In [61]:
np.linalg.eig(a)
help(np.linalg.eig)

Help on function eig in module numpy.linalg.linalg:

eig(a)
    Compute the eigenvalues and right eigenvectors of a square array.
    
    Parameters
    ----------
    a : (..., M, M) array
        Matrices for which the eigenvalues and right eigenvectors will
        be computed
    
    Returns
    -------
    w : (..., M) array
        The eigenvalues, each repeated according to its multiplicity.
        The eigenvalues are not necessarily ordered. The resulting
        array will be of complex type, unless the imaginary part is
        zero in which case it will be cast to a real type. When `a`
        is real the resulting eigenvalues will be real (0 imaginary
        part) or occur in conjugate pairs
    
    v : (..., M, M) array
        The normalized (unit "length") eigenvectors, such that the
        column ``v[:,i]`` is the eigenvector corresponding to the
        eigenvalue ``w[i]``.
    
    Raises
    ------
    LinAlgError
        If the eigenvalue computation does not 

In [157]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [158]:
b = a.T

In [159]:
b

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [160]:
np.dot(a,b)


array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

In [187]:
a = np.array([1,1,0], dtype = bool)
b = np.array([1,0,1], dtype = bool)


In [176]:
np.logical_or(a,b)

array([ True,  True,  True], dtype=bool)

In [188]:
np.logical_and(a,b)

array([ True, False, False], dtype=bool)

In [189]:
np.all(a == a)

True

In [179]:
a = np.array([[1,2],[3,4]])

In [6]:
a


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
a.sum()

45

In [8]:
a.sum(axis=0)

array([12, 15, 18])

In [11]:
a.sum(axis=1)

array([ 6, 15, 24])

In [12]:
a.max()

9

In [22]:
a.argmax()

5

In [20]:
a=np.array([[1,5,2],[3,1,8]])

In [21]:
a.shape

(2, 3)

In [17]:
a[:,np.newaxis].shape # adds a new axis -> 2D

(3, 1, 3)

In [25]:
np.sort(a)

array([[1, 2, 5],
       [1, 3, 8]])

In [27]:
np.argsort(a)
help(np.argsort)

Help on function argsort in module numpy.core.fromnumeric:

argsort(a, axis=-1, kind='quicksort', order=None)
    Returns the indices that would sort an array.
    
    Perform an indirect sort along the given axis using the algorithm specified
    by the `kind` keyword. It returns an array of indices of the same shape as
    `a` that index data along the given axis in sorted order.
    
    Parameters
    ----------
    a : array_like
        Array to sort.
    axis : int or None, optional
        Axis along which to sort.  The default is -1 (the last axis). If None,
        the flattened array is used.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
        Sorting algorithm.
    order : str or list of str, optional
        When `a` is an array with fields defined, this argument specifies
        which fields to compare first, second, etc.  A single field can
        be specified as a string, and not all fields need be specified,
        but unspecified fields w

In [29]:
np.argsort(a)

array([[0, 2, 1],
       [1, 0, 2]], dtype=int64)

In [31]:
np.sort(a)

array([[1, 2, 5],
       [1, 3, 8]])

In [32]:
a

array([[1, 5, 2],
       [3, 1, 8]])

In [38]:
a=np.array([[11,12,14],[9,10,12],[34,45,0]])

In [39]:
a.argmin()

8